# Generated by Django 5.0.3 on 2024-03-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_buyer_options_alter_vendor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyer'},
        ),
    ]
