# Generated by Django 5.0.3 on 2024-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_buyer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='name'),
        ),
    ]
