# Generated by Django 5.0.3 on 2024-03-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_buyer_name_remove_vendor_name_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (('can_see_link', 'Can see the link'),), 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendor'},
        ),
    ]
