# Generated by Django 4.2.11 on 2024-03-21 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_username_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_born',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_of_registration'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
