# Generated by Django 4.2.11 on 2024-03-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_date_born_profile_date_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_of_registration'),
        ),
    ]
