# Generated by Django 4.2.11 on 2024-03-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_group_profile_location_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Name Field'),
        ),
    ]
