# Generated by Django 4.2.11 on 2024-03-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_goods_mini_rubric_goods_rubric_and_more'),
        ('user', '0012_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.ManyToManyField(to='shop.goods'),
        ),
    ]
