# Generated by Django 4.2.11 on 2024-04-11 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_goods_photo_good'),
        ('user', '0013_profile_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ManyToManyField(to='shop.goods')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
