# Generated by Django 4.2.11 on 2024-04-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_profile_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=':', max_length=100, verbose_name='Напишите ваш адрес'),
        ),
    ]
