# Generated by Django 4.2.11 on 2024-09-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Напишите ваш адрес'),
        ),
    ]
