# Generated by Django 5.0.3 on 2024-03-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('short_information', models.CharField(max_length=50, verbose_name='short_information')),
                ('information', models.TextField(verbose_name='information')),
                ('cost', models.FloatField(verbose_name='cost')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date_of_new')),
            ],
        ),
        migrations.CreateModel(
            name='Mini_Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_rubric_title', models.CharField(max_length=50, verbose_name='rubric')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_title', models.CharField(max_length=50, verbose_name='rubric')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('text', models.TextField()),
                ('date_comment', models.DateTimeField(auto_now_add=True, verbose_name='date_of_new')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.goods', verbose_name='goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='mini_rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.mini_rubric', verbose_name='mini_rubric'),
        ),
        migrations.AddField(
            model_name='mini_rubric',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.rubric', verbose_name='rubric'),
        ),
    ]
