# Generated by Django 5.0.3 on 2024-03-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='mini_rubric',
        ),
        migrations.AddField(
            model_name='goods',
            name='rubric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.rubric', verbose_name='rubric'),
        ),
        migrations.DeleteModel(
            name='Mini_Rubric',
        ),
    ]
