# Generated by Django 4.2.11 on 2024-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_goods_mini_rubric_goods_rubric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo_good',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
