# Generated by Django 4.2.11 on 2024-09-26 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_goods_photo_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
            preserve_default=False,
        ),
    ]
